### ISSUE TITLE
/etc/localtime does not always work

### ISSUE THREAD

**Issue by leofonic** [proudcommerce/docker-oxid6#12]
/etc/localtime in volume mapping causes error "OCI runtime create failed" on windows and mac sometimes. There are lots of reports about this e.g. https://github.com/docker/for-mac/issues/2396 but i don't have a clue how to resolve it, i removed all mappings to /etc/localtime and the container started ok.

**Comment by marvpaul** [comment]
Same problem here. This fix also worked for me: https://github.com/docker/for-mac/issues/2396#issuecomment-370033847

**Comment by proudcommerce** [comment]
https://github.com/proudcommerce/docker-oxid6/commit/1a6334b4678ef2391d2b85feb1c8bdbaa61643e7
