### ISSUE TITLE
Problem when building: "The Compose file './docker-compose.yml' is invalid because"

### ISSUE THREAD

**Issue by PellelNitram** [proudcommerce/docker-oxid6#8]
Hi,

I have an issue when attempting to build the container according to the Quickstart section of the readme.

This is the issue that I am facing:

![Screenshot from 2019-07-22 16-08-17](https://user-images.githubusercontent.com/2728265/61639248-653e4980-ac9b-11e9-918e-da4e2b2a2d34.png)

Do you might know the cause for this issue?

Best wishes and thank you in advance,
Martin

**Comment by proudcommerce** [comment]
reverted changes for the moment

**Comment by Franselbaer** [comment]
Might be invalid Version in first line. Try 2.5 or 2.2 or 3. Will have a look later on.
